In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [102]:
train_df = pd.read_csv("annotations_train.csv",header=None)
train_df

                      0     1     2     3     4       5     6     7
0           train_0.jpg   208   537   422   814  object  3024  3024
1           train_0.jpg  1268  1923  1365  2209  object  3024  3024
2           train_0.jpg  1135  2074  1261  2166  object  3024  3024
3           train_0.jpg  1045  2085  1122  2258  object  3024  3024
4           train_0.jpg   976  2036  1040  2177  object  3024  3024
...                 ...   ...   ...   ...   ...     ...   ...   ...
1048571  train_7440.jpg  1614   276  1736   373  object  1920  2560
1048572  train_7440.jpg  1379   332  1480   419  object  1920  2560
1048573  train_7440.jpg  1272   346  1368   439  object  1920  2560
1048574  train_7440.jpg  1188   392  1264   464  object  1920  2560
1048575  train_7440.jpg  1103   410  1174   483  object  1920  2560

[1048576 rows x 8 columns]

In [103]:
def split_function(row):
    row = row.split("_")
    row = row[1]
    row = row.split(".")
    row = row[0]
    return row
def convert_train(row):
    row = str(row)
    opt_row = f"train_{row}.jpg"
    return opt_row

In [104]:
train_df[0] = train_df[0].apply(split_function)
train_df[0] = train_df[0].astype(int)
train_df = train_df[train_df[0]<=200]
train_df[0] = train_df[0].apply(convert_train)
train_df.reset_index(inplace=True)
train_df = train_df.iloc[:,1:]
train_df.to_csv("train_ant.csv",index=None,header=None)

C:\Users\jzulfiqar\AppData\Local\Temp\ipykernel_21500\2962573220.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[0] = train_df[0].apply(convert_train)